Rewrite dm-setbg

diff --git a/scripts/dm-setbg b/scripts/dm-setbg
--- a/scripts/dm-setbg
+++ b/scripts/dm-setbg
@@ -1,27 +1,12 @@
 #!/usr/bin/env bash
 
 # Script name: dm-setbg
-# Description: A wallpaper setting utility using dmenu, xwallpaper and sxiv
-# Also has the following features
-# 1. set a random walllpaper
-# 2. draw your last wallpaper at startx
-# 3. Change wallpaper after every second(go insane)
-
-# Dependencies: dmenu, xwallpaper, sxiv
+# Description: A wallpaper setting utility using dmenu, imv and swaybg/xwallpaper
+# Dependencies: dmenu, xwallpaper or swaybg, imv
 
 # Contributors: Murtaza Udaipurwala
 #               HostGrady
 #               Simon Ingelsson
-
-## Usage
-# run dm-setbg without any argument to get a dmenu prompt
-# dm-setbg [optional arguments]
-# -h    Displays this help menu
-# -d    draws the wallpaper at startx. Add 'dm-setbg -d' in your xinitrc
-# -r    randomly selects a wallpaper
-# -i    Go insane
-
-# Note this script is posix compliant
 
 # Set with the flags "-e", "-u","-o pipefail" cause the script to fail
 # if certain things happen, which is a good thing.  Otherwise, we can
@@ -41,74 +26,43 @@ fi
 # shellcheck disable=SC1090
 source "$(get_config)"
 
-
-help() {
-    # shellcheck disable=SC2154
-    printf '
-    ## Usage
-    run dm-setbg without any argument to select a wallpaper from %s\n
-    dm-setbg [optional arguments]
-    -h\tDisplays this help menu
-    -d\tdraws the wallpaper at startx. Add "dm-setbg -d" in your xinitrc
-    -r\trandomly selects a wallpaper
-    -i\tGo insane
-' "${setbg_dir}"
-}
-
-change() {
-    xwallpaper --stretch "$1" 2>/dev/null
-}
-
-shuffle() {
-    wallpaper=$(find "${setbg_dir}" -type f | shuf -n 1)
-    echo "$wallpaper"
-}
-
+# Set wallpaper using either xwallpaper or swaybf
 setbg() {
-    wallpaper="$(sxiv -t -o "${setbg_dir}")"
-    echo "$wallpaper" > "$HOME"/.cache/wall
-    change "$wallpaper"
+  case "$XDG_SESSION_TYPE" in
+    'x11') xwallpaper --stretch "$1";;
+    'wayland') swaybg -m "stretch" -i "$1";;
+    *) err "Unknown display server";;
+  esac
 }
 
-# draw the wallpaper at startx
-draw() {
-    change "$(cat "$HOME"/.cache/wall)"
-}
-
-random() {
-    wallpaper=$(shuffle)
-    echo "$wallpaper" > "$HOME"/.cache/wall
-    change "$wallpaper"
-}
-
-goInsane() {
-    while true; do
-        wallpaper=$(shuffle)
-        change "$wallpaper"
-        sleep 1s
+main() {
+  choice="$(printf "Set\nRandom\nExit" | "${DMENU}" "What would you like to do?")" 
+  case "$choice" in
+    "Set") 
+    # Read each line printed to stdin, imv behaves weird
+    # We also ignore a shellcheck issue because it's a bug
+    # shellcheck disable=SC2154
+    imv "${setbg_dir}" | while read -r LINE; do
+      killall "swaybg" 2>/dev/null
+      killall "xwallpaper" 2>/dev/null
+      setbg "$LINE" & # Sets the wallpaper and frees it from the process
+      notify-send "Wallpaper has been updated" "$LINE is the current wallpaper, edit your window manager config if you would like this to persist on reboot"
     done
+    ;;
+    "Random")
+    valid_paper="No"
+    until [ "$valid_paper" = "Yes" ]; do
+      killall "swaybg" 2>/dev/null
+      killall "xwallpaper" 2>/dev/null
+      wallpaper="$(find "${setbg_dir}" -type f | shuf -n 1)"
+      setbg "$wallpaper"
+      cp "$wallpaper" "$HOME/.cache/wall"
+      valid_paper="$(printf "Yes\nNo" | "${DMENU} Do you like the new wallpaper?")"
+    done
+    ;;
+    "Exit") echo "Program terminated" && exit 1;;
+    *) err "Invalid choice";;
+  esac
 }
 
-# dmenu menu
-menu() {
-    # options="set background\nrandom\ngo insane"
-    input=$(printf "set background\nrandom\ngo insane" | ${DMENU} "Select an option:") || exit 1
-    case "$input" in
-        "set background") setbg ;;
-        "random") random ;;
-        "go insane") goInsane ;;
-    esac
-}
-
-noOpt=1
-while getopts "hdrim" arg 2>/dev/null; do
-    case "${arg}" in
-        h) help ;;
-        d) draw ;;
-        r) random ;;
-        i) goInsane ;;
-        *) printf "invalid option\nType dm-setbg -h for help" ;;
-    esac
-    noOpt=0
-done
-[ $noOpt = 1 ] && menu
+[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
