Some cleanup to make shellcheck happy, we still need to get a good structure in place

diff --git a/scripts/dm-usbmount b/scripts/dm-usbmount
--- a/scripts/dm-usbmount
+++ b/scripts/dm-usbmount
@@ -6,11 +6,11 @@
 # Author: Murtaza Udaipurwala
 
 help(){
-    printf "dm-usbmount [options]\n
+    printf 'dm-usbmount [options]\n
     -h\tDisplays this help menu
     -m\tMount usb drive
     -u\tUnmount usb drive\n
-    Drives are mounted at /run/media\n"
+    Drives are mounted at /run/media\n'
 }
 
 driveCount(){
@@ -38,8 +38,12 @@ mount(){
     driveCount "$mountable"
     [ "$count" = "1" ] && options="$mountable" || options="$mountable\nall"
 
-    chosen="$(printf "$options" | dmenu -i -p "Drive to mount?")" || exit
-    [ "$chosen" = "all" ] && mountAll || udisksctl mount -b "${chosen%% *}"
+    chosen="$(printf '%s' "$options" | dmenu -i -p "Drive to mount?")" || exit
+    if [ "$chosen" = "all" ]; then
+       mountAll 
+    else 
+        udisksctl mount -b "${chosen%% *}"
+    fi
 }
 
 unmount(){
@@ -49,8 +53,12 @@ unmount(){
     driveCount "$mounted"
     [ "$count" = "1" ] && options="$mounted" || options="$mounted\nall"
 
-    chosen="$(printf "$options" | dmenu -i -p "Drive to unmount?")"
-    [ "$chosen" = "all" ] && unmountAll || udisksctl unmount -b "$chosen"
+    chosen="$(printf '%s' "${options}" | dmenu -i -p "Drive to unmount?")"
+    if [ "$chosen" = "all" ] ; then 
+       unmountAll 
+   else
+       udisksctl unmount -b "$chosen"
+    fi
 }
 
 while getopts "hmu" arg 2>/dev/null; do
@@ -58,6 +66,6 @@ while getopts "hmu" arg 2>/dev/null; do
         h) help ;;
         m) mount ;;
         u) unmount ;;
-        *) echo "invalid option\nType dm-usbmount -h for help" ;;
+        *) printf "invalid option\nType dm-usbmount -h for help" ;;
     esac
 done
